services:
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  fastapi:
    build:
      context: .
    ports:
      - "${app_port}:${app_port}"
    volumes:
      - ./src/tests:/app/tests
    environment:
      - PORT=${app_port}
      - KEY=${jwt_secret_key}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - rabbitmq
      - db
  consumer:
    build:
      context: .
    command: ["sh", "-c", "sleep 30 && python src/consumers/image_processor/consumer.py"]
    env_file:
      - ".env"
