version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"      # основной порт для AMQP
      - "15672:15672"    # порт веб-менеджера
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  fastapi:
    build:
      context: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - KEY=${KEY}
      - RABBITMQ_HOST=rabbitmq  # переменная для подключения к RabbitMQ
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    depends_on:
      - rabbitmq
