services:
  rabbitmq:
    image: rabbitmq:3.12-management
    env_file:
      - .env
    ports:
      - "${rabbitmq_port}:${rabbitmq_port}"
      - "${rabbitmq_management_port}:${rabbitmq_management_port}"

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "${postgres_port}:${postgres_port}"

  fastapi:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "${app_port}:${app_port}"
    volumes:
      - ./src/tests:/app/tests
    depends_on:
      - rabbitmq
      - db
  consumer:
    build:
      context: .
    command: ["sh", "-c", "sleep 15 && python src/consumers/image_processor/consumer.py"]
    env_file:
      - ".env"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./src/prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml
    env_file:
      - .env
    ports:
      - "${prometheus_port}:${prometheus_port}"

  grafana:
    image: grafana/grafana
    env_file:
      - .env
    ports:
      - "${grafana_port}:${grafana_port}"